### ISSUE TITLE
Comportements inconsistants avec l'action builder

### ISSUE THREAD

**Issue by thom4parisot** [YesWiki/yeswiki#618]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**

Je rencontre plusieurs problèmes en créant un fichier `actions/documentation.yml` dans une extension.

1. Une action sans paramètre n'est pas sélectionnable.

```yaml
label: "Publication"
actions:
  blankpage:
    label: "Bouton : insérer une page vide"
    description: À insérer dans une page de contenu, pour insérer une page vide lors de la génération de la publication.
```

![image](https://user-images.githubusercontent.com/138627/105883983-c0c36300-6007-11eb-95e3-5e9bf5d89e12.png)

2. Le passage d'une action à paramètres à une action sans paramètre préserve les attributs

D'abord une action avec paramètres : 

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/138627/105884286-1bf55580-6008-11eb-8afb-afbfa2b7601c.png">

Puis en bascultant vers la précédente action sans paramètres : 

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/138627/105884374-36c7ca00-6008-11eb-8922-7635dd47d80a.png">

**Problème** : le formulaire et le code à insérer restent identiques à la précédente action.

3. Une action qui se nomme `bazar2publication` est prise pour `bazarliste`

```yaml
label: "Publication"
actions:
  bazar2publication:
    label: Impression de résultats Bazar
    description: Bouton à positionner à côté d'une action.
    properties:
      title:
        label: Titre
        type: text
```

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/138627/105884590-67a7ff00-6008-11eb-8c07-4f10f19989b4.png">

**Additionnal informations / Informations complémentaires**
- version of YesWiki / branche `doryphore@083a7569ad`
